### ISSUE TITLE
Amplitude distance calculation doesn't corresponding with literature

### ISSUE THREAD

**Issue by tonetechnician** [mmontag/wfs-designer#3]
Hey Matt, 

Great work on this. I know I'm sort of resurrecting something from the 2014 grave here, but if you could help I'd be super appreciative!!! I have been wondering what literature you based your distance calculation for the amplitude of a nominal source? 

I've read through your thesis and it seems to me that your distance and listener compensation equations for the driving signal for each speaker (from chapter 2) do not correspond with the calculation you use in your software ( \sqrt{B/(A+B)} where A=source -> loudspeaker and B = loudspeaker -> listener. 

Would you be able to shed any light on why you chose to use this calculation instead of the one in the literature?

Much thanks!

**Comment by mmontag** [comment]
Hi,

Oh, I'm embarrassed, that code is pretty messy. See equation 33 in this paper https://pdfs.semanticscholar.org/cafe/e6d5e8a599113545bec3e297c146ee6fa091.pdf:
![image](https://user-images.githubusercontent.com/946117/47080490-f9372e00-d1bc-11e8-8b7a-9544fa3f628f.png)

The big radical term matches my gain calculation. 
But it's been too long, I can't remember why. Maybe I made an error.

**Comment by tonetechnician** [comment]
No, don't stress! Haha, masters projects are like this (I'm finishing mine currently).

I see now.  Thanks so much for the source. I think the term that might be missing is the division by the square root of the distance of source to the loudspeaker i.e 

![image](https://user-images.githubusercontent.com/13471797/47136078-da1ac800-d2b2-11e8-9178-eaac5bd46ed5.png)

Thanks again in any case! 
All the best, 

Sean
